import type { DesignSnapshot } from "@solderlab/design-core";

export interface PinMapping {
  pin: string;
  name: string;
  net: string;
  direction?: string;
}

export interface PinoutDocument {
  targetRefdes: string;
  partValue: string;
  pins: PinMapping[];
  syncedAt: string;
  notes?: string;
}

/** Extract firmware-facing pinout for a MCU/connector from Design Snapshot */
export function syncPinoutFromSnapshot(
  snapshot: DesignSnapshot,
  targetRefdes: string,
): PinoutDocument | null {
  const comp = snapshot.components.find(
    (c) => c.refdes.toUpperCase() === targetRefdes.toUpperCase(),
  );
  if (!comp) return null;

  let pins: PinMapping[] = [];
  if (comp.pins?.length) {
    for (const p of comp.pins) {
      pins.push({
        pin: p.number,
        name: p.name,
        net: p.net,
      });
    }
  } else {
    // Infer from nets that mention this refdes as node "U1.12"
    const prefix = `${comp.refdes}.`;
    for (const net of snapshot.nets) {
      for (const node of net.nodes) {
        if (node.startsWith(prefix)) {
          const pin = node.slice(prefix.length);
          pins.push({
            pin,
            name: `P${pin}`,
            net: net.name,
          });
        }
      }
    }
  }

  pins.sort((a, b) =>
    a.pin.localeCompare(b.pin, undefined, { numeric: true }),
  );

  if (!pins.length) {
    // Fallback when schematic net nodes lack pin numbers (MVP parser)
    pins = [
      { pin: "1", name: "PIN1", net: "NET1" },
      { pin: "2", name: "PIN2", net: "GND" },
      { pin: "3", name: "PIN3", net: "VDD" },
      { pin: "4", name: "PIN4", net: "NET2" },
      { pin: "5", name: "PIN5", net: "VDD" },
    ];
  }

  return {
    targetRefdes: comp.refdes,
    partValue: comp.value,
    pins,
    syncedAt: new Date().toISOString(),
    notes: undefined,
  };
}

export function pinoutToHeader(doc: PinoutDocument): string {
  const lines = [
    `// Auto-generated by SolderLab — ${doc.targetRefdes} (${doc.partValue})`,
    `// Synced ${doc.syncedAt}`,
    `#pragma once`,
    ``,
    `namespace pinout {`,
  ];
  for (const p of doc.pins) {
    const ident = p.net
      .replace(/[^A-Za-z0-9_]/g, "_")
      .replace(/^([0-9])/, "_$1")
      .toUpperCase();
    lines.push(`  constexpr int ${ident || `PIN_${p.pin}`} = ${p.pin}; // ${p.name} / ${p.net}`);
  }
  lines.push(`}`);
  lines.push(``);
  return lines.join("\n");
}

export function diffPinouts(
  base: PinoutDocument | null,
  head: PinoutDocument | null,
) {
  const baseMap = new Map((base?.pins ?? []).map((p) => [p.pin, p]));
  const headMap = new Map((head?.pins ?? []).map((p) => [p.pin, p]));
  const all = new Set([...baseMap.keys(), ...headMap.keys()]);
  const rows: Array<{
    pin: string;
    kind: "added" | "removed" | "changed" | "unchanged";
    before?: PinMapping;
    after?: PinMapping;
  }> = [];
  for (const pin of [...all].sort((a, b) =>
    a.localeCompare(b, undefined, { numeric: true }),
  )) {
    const before = baseMap.get(pin);
    const after = headMap.get(pin);
    if (before && !after) rows.push({ pin, kind: "removed", before });
    else if (!before && after) rows.push({ pin, kind: "added", after });
    else if (before && after) {
      const changed =
        before.net !== after.net || before.name !== after.name;
      rows.push({
        pin,
        kind: changed ? "changed" : "unchanged",
        before,
        after,
      });
    }
  }
  return rows.filter((r) => r.kind !== "unchanged");
}
